#!/usr/bin/env bash

APP="baz" # name of your release

BUILD_HOST="159.203.79.224" # host where to build the release
BUILD_USER="root" # local user at build host
BUILD_AT="/tmp/erlang/baz/builds" # build directory on build host

STAGING_HOSTS="159.203.79.224" # staging / test hosts separated by space
STAGING_USER="root" # local user at staging hosts
TEST_AT="/test/baz" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="159.203.79.224" # deploy / production hosts separated by space
PRODUCTION_USER="root" # local user at deploy hosts
DELIVER_TO="/opt/baz" # deploy directory on production hosts
